[package]
name        = "ikpir-server"
description = "Server library for Incremental-Keyword-PIR with incremental insert/delete/update."

version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
license.workspace      = true

readme = "README.md"

autobenches = false

[lints]
workspace = true

[dependencies]
ikpir-common            = { workspace = true }
segmented-cuckoo-filter = { workspace = true }
rand         = { workspace = true }
rand_chacha  = { workspace = true }

[dev-dependencies]
ikpir-client = { workspace = true }

[[bench]]
name    = "setup_latency"
harness = false

[[bench]]
name    = "query_latency"
harness = false

[[bench]]
name    = "insert_cost"
harness = false

[[bench]]
name    = "delete_cost"
harness = false

[[bench]]
name    = "full_rebuild_vs_incremental"
harness = false
