[package]
name        = "ikpir-common"
description = "Shared primitives for Incremental-Keyword-PIR: LWE, matrix, keyword encoding."

version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
license.workspace      = true

readme = "README.md"

[lints]
workspace = true

[dependencies]
segmented-cuckoo-filter = { workspace = true }
rand        = { workspace = true }
rand_chacha = { workspace = true }
xxhash-rust = { workspace = true }
