[package]
name        = "ikpir-client"
description = "Client library for Incremental-Keyword-PIR."

version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
repository.workspace   = true
license.workspace      = true

readme = "README.md"

[lints]
workspace = true

[dependencies]
ikpir-common = { workspace = true }
rand         = { workspace = true }
rand_chacha  = { workspace = true }
